name: test-workflow-action

on: 
  push:
    branches:
      - master

jobs:
  test-express-application:

    runs-on: Ubuntu-latest
    steps:
      - name: Starting test workflow
        uses: actions/checkout@v3

      - name: Setting up node environment
        uses: actions/setup@v3
        with: 
          node-version: '14'

      - name: Installing dependencies
      - run: npm i

      - name: Running test
        run: npm test